import { requirePropFactory } from '@material-ui/core';
import React, { Component } from 'react';
import './styles.css';

export default class Board extends Component {
  render() {
    return (
        <div className="board">
            <p>Vivemos em uma bolha atmosférica que possui as perfeitas condições para nossa existência, durante os últimos 4.5 bilhões de anos a terra teve, em média, temperaturas ou extremamente altas, ou extremamente baixas, devido à alguns fatores como posição da terra em relação ao sol, gases de efeito estufa, eventos e condições geotérmicas ou geofísicas. </p>
            <p>Essa bolha passou a existir alguns milhões de anos atrás, e irá inevitavelmente acabar um dia, acabando com a nossa existência, e dando lugar a espécies mais bem adaptadas ao novo ambiente (ou acabando com toda a vida), mas evidências nos mostram que a atividade humana tem aumentado por meio de vários termos a temperatura média da terra, e a pergunta capital desse século é se podemos fazer algo a respeito e se continuarmos nesse ritmo podemos acabar estourando essa benevolente bolha prematuramente.</p>
            <p>Entender o aquecimento global e mudanças climáticas é uma tarefa um pouco mais complicada que simplesmente olhar gráficos da concentração de gás carbônico, já que o clima é multifatorial, e a concentração de CO2 é apenas um desses fatores, que interagem entre si em um sistema quase caótico.</p>
            <p>Um modelo climático real é muito mais complexo, e contém vários eventos e efeitos aninhados que interagem entre si e se sobrepõem em looping, tais modelos ainda não existem e são somente aproximados, por isso, modelos climáticos que realmente se aproximem da realidade ainda são impossíveis por uma limitação de hardware.</p>
            <p>Vapor de água, ao contrário do que diz o senso comum, é o gás de efeito estufa que mais contribui para o efeito estufa, representado 95% de sua totalidade, enquanto CO2 representa apenas 3.618%, e menos de 3% desse CO2 é produzido pelo homem, mas isso não significa que o aquecimento global não é causado pelo homem, já que, como eu disse antes, o clima é algo multifatorial e esses fatores interagem entre si de maneiras muito mais complexas do que um gráfico ou dado pode mostrar.</p>
            <p>A politização do aquecimento global nos últimos anos infelizmente não tem contribuído para a pesquisa no tópico, muito menos para seu combate, por isso, alguns dados obtidos por instituições filiadas a governos podem ser desacreditados ou até comprometidos, o que dificulta o trabalho científico, e o fato de que o tempo local não pode ser medido com precisão com uma semana de antecedência faz com que muitos da comunidade não-científica questionem como cientistas conseguem saber a temperatura média e condições climáticas há 50, 100, 100.000 ou até 1 milhão de anos atrás, mas não sabem se fará sol amanhã, o que é uma comparação um tanto injusta já que tempo e clima são duas coisas diferentes.</p>
            <img src={require("../../assets/temperatureOfThePlanet.png")}/>
            <p>Uma visão geral da temperatura da terra nos últimos 500 milhões de anos nos mostra uma certa estabilização da temperatura média do planeta nas últimas dezenas de milhares de anos, vale ressaltar que o homo sapiens surgiu por volta de 200.000 anos atrás, pelo fim do Pleistoceno, do período Quaternário da era Cenozoica.</p>
            <img src={require("../../assets/historicalCO2Level.png")}/>
            <img src={require("../../assets/tempCO2Graph.png")}/>
            <p>Olhando para dados mais recentes e comparações entre a concentração de CO2 e a temperatura global média podemos ver uma incontestável relação entre os dois, o aumento na concentração de CO2 resulta em um aumento na temperatura global, e estudos apontam que esse aumento no CO2 precede os aumentos na temperatura em cerca de 400 anos, algo que voltarei a falar depois.</p>
            <p>Algo notável são os ciclos de em média 90.000 anos e o recente pico de CO2, esses ciclos são comumente associados a eras glaciais, onde os picos representam eras interglaciais. A média de CO2 atualmente é significantemente maior do que nos últimos milhares de anos, levantando questões sobre a continuidade desse ciclo.</p>
            <p>Uma pergunta que pode ser levantada é: se o ser humano produz menos de 3% de todo o gás carbônico como pode existir esse pico na concentração de CO2 justamente por volta do início da primeira revolução industrial?</p>
            <p>Aí que a característica multifatorial do clima se apresenta, a quantidade de gás carbônico emitida por indústrias, carros, navios, por si só não é o suficiente para criar esse pico, mas quando se leva em conta o fato de que o ser humano destruiu os maiores reguladores naturais de CO2: as florestas húmidas e os fitoplânctons, mudanças no CO2 se tornam mais dramáticas, e as alterações naturais de CO2 se tornam descontroladas</p>
            <img src={require("../../assets/petroliferas.png")}/>
            <p>Os danos causados por indústrias petrolíferas e madeireiras é muito maior do que o dano causado por indústrias que simplesmente emitem gás carbônico, pois estas destroem os agentes controladores de gases de efeito estufa, causando o mais simples caos.</p>
            <p>Vulcões, fotossíntese, decomposição orgânica e metabolismo animal são algumas das principais fontes ou depósitos de CO2 e O2 no planeta, apesar de que pouco sabe-se sobre essa relação entre CO2, O2 e energia, sabe-se que: animais e plantas vivem em uma relação simbiótica necessária para a sobrevivência, animais consumem oxigênio e carbono e produzem CO2, plantas consumem CO2 e energia solar e produzem oxigênio e carbono, esse paradigma permaneceu inalterado durante os últimos 2 milhões de anos, pois a população era pequena demais para se levar o espaço em conta. </p>
            <p>O gênero Homo apareceu por volta de 2.8 milhões de anos atrás, homo erectus 1.8 milhões de anos, homo sapiens por volta de 200.000 anos, a população humana mais antiga de que se tem registro data de 12.000 anos atrás, a população total na época é estimada em 4 milhões de pessoas, hoje em dia são 7.7 bilhões e a taxa de variação é de 1.4%/ano. Na época cada pessoa tinha em torno de 15km² de terra habitável, comida e água, hoje em dia o número é de 0.009km², então, naturalmente o ser humano começou a devastar rios e florestas para encontrar mais espaço.</p>
            <img src={require("../../assets/worldPopulation.png")}/>
            <img src={require("../../assets/worldPopvsCO2.png")}/>
            <p>O gráfico acima mostra a relação entre a emissão de gás carbônico e o aumento populacional.</p>
            <p style={{ fontStyle: "italic", marginTop:"1%" }}>O aumento no nível do mar:</p>
            <p style={{ fontStyle: "italic" }}>“Aumento no nível do mar é um dos efeitos da mudança climática, a média do nível do mar aumentou mais de 23 cm desde 1880, todo o ano o mar sobe mais 3.2mm. A mudança no nível do mar está ligada a três fatores principais, todos induzidos pelas mudanças climáticas globais em andamento:</p>
            <p style={{ fontStyle: "italic" }}>Expansão térmica: quando a água esquenta, ela se expande. Cerca de metade da elevação do nível do mar nos últimos 25 anos é atribuída aos oceanos mais quentes, que simplesmente ocupam mais espaço.</p>
            <p style={{ fontStyle: "italic" }}>Geleiras derretendo: Grandes formações de gelo, como as geleiras das montanhas, derretem naturalmente um pouco a cada verão. No inverno, as neves, principalmente da água do mar evaporada, são geralmente suficientes para equilibrar o derretimento. Recentemente, porém, temperaturas persistentemente mais altas causadas pelo aquecimento global levaram a um derretimento acima da média no verão, bem como a uma queda de neve diminuída devido a invernos posteriores e nascentes anteriores. Isso cria um desequilíbrio entre o escoamento e a evaporação do oceano, causando o aumento do nível do mar.</p>
            <p style={{ fontStyle: "italic" }}>Perda das camadas de gelo da Groenlândia e da Antártica: como nas geleiras das montanhas, o aumento do calor está fazendo com que as enormes camadas de gelo que cobrem a Groenlândia e a Antártica derretam mais rapidamente. Os cientistas também acreditam que a água derretida de cima e a água do mar de baixo estão vazando sob as camadas de gelo da Groenlândia, lubrificando efetivamente as correntes de gelo e fazendo com que elas se movam mais rapidamente para o mar. Embora o derretimento na Antártida Ocidental tenha atraído um foco considerável de cientistas, especialmente com a quebra de 2017 na plataforma de gelo Larsen C, as geleiras da Antártida Oriental também estão mostrando sinais de desestabilização.”</p>
            <p>- National Geographic</p>
            <p style={{ marginTop: "1%" }}>Durante os últimos 800 mil anos é observável uma clara relação entre o nível do mar e a temperatura global média</p>
            <img src={require("../../assets/seaLevelTemp.png")}/>
            <p>Sendo o clima um modelo extremamente complexo e multifatorial, analisa-lo de maneira abrangente é uma tarefa difícil, por exemplo, no começo citei que mudanças no CO2 induzem mudanças na temperatura com um atraso de 400 anos, porém, esse atraso claramente se tornou menor nos últimos 10.000 anos, por motivos ainda desconhecidos.</p>
            <img src={require("../../assets/tabela.png")}/>
            <p>A tabela acima mostra alguns dados das taxas de variação das funções para temperatura global, nível do mar e concentração de CO2, ou melhor falando, as derivadas de cada função suavizada com respeito ao tempo. E elas tem caído.</p>
            <p>Se os padrões estabelecidos nos últimos 800.000 anos continuarem, então não temos o que temer, mas os recentes picos na concentração de CO2, e principalmente aumento nas taxas de variação de CO2, nível do mar, temperatura global e população mostram um padrão a ser observado, já que existe uma correlação, ainda não comprovadamente causa e efeito, entre estes fatores e muitos outros que compõe o clima global.</p>
        </div>
    );
  }
}
